#!/usr/bin/env node

/**
 * Module dependencies.
 */

var requirejs = require('requirejs')
  , program = require('commander')
  , pjson = require('../package.json')
  , cf = require('../configurations/program')
  , tmpl = requirejs('../build/tmpl');

var footerInfo = require('../components/footerInfo');

program
  .version(pjson.version)
  .option('-l, --locale <locale>', 'specify locale', String, cf.DEFAULT_LOCALE);

program
  .command('generate [name]')
  .description('generate email templates')
  .action(function(name, options) {
    var hero = require('../components/hero')(this.locale);
    var promos = require('../components/promos')(this.locale);
    if(name == "tantanInvitation"){
      console.log(this.locale + name);
      // return (tmpl.html);
      console.log(tmpl.html({
        hero : tmpl.hero({ hero : hero}),
        promos : tmpl.promos({ promos : promos}),
        footer : tmpl.footer({ footerInfo : footerInfo})
      }));
    }
    else console.log("no template for this");
  });

program.parse(process.argv);
